services:
  db:
    image: postgres:16
    container_name: db_betarget
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env-non-dev

  redis:
    image: redis:7
    container_name: redis_betarget
    command: --port 5370
    expose:
      - 5370
    env_file:
      - .env-non-dev

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: betarget
    command: ["/betarget/docker/app.sh"]
    ports:
      - 9999:8080
    depends_on:
      - db
      - redis
