version: '3.9'

services:
  db:
    image: postgres:16
    restart: always
    container_name: db_betarget_backend
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    expose:
      - 1221
    ports:
      - "${DB_PORT}:1221"
    env_file:
      - .env

  db-test:
    image: postgres:16
    container_name: test_db_betarget_backend
    environment:
      POSTGRES_DB: ${DB_TEST_NAME}
      POSTGRES_USER: ${DB_TEST_USER}
      POSTGRES_PASSWORD: ${DB_TEST_PASS}
    expose:
      - 5432
    ports:
      - "${DB_TEST_PORT}:5432"
    env_file:
      - .env

  redis:
    image: redis:7
    restart: always
    container_name: redis_betarget_backend
    command: --port 5370
    expose:
      - 5370
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3.13.4-management
    restart: always
    container_name: rabbitmq_betarget_backend
    expose:
      - 5672
      - 15672

  app:
    build: .
    container_name: app_betarget_backend
    restart: always
    ports:
      - 9999:8080
    command: ["sh", "./docker/app.sh"]
    env_file:
      - .env
    volumes:
      - ./logs:/betarget_backend/logs
      - ./migrations/versions:/betarget_backend/migrations/versions
    depends_on:
      - db
      - db-test
