name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Chrome
        uses: sudo apt-get install google-chrome-stable

      - name: install dependencies
        uses: pip install -r requirements.txt

      - name: Run tests
        uses: pytest -v backend/tests/